name: 'Auto Issue Author Assign'
description: 'Assign author to issue when issue are opened.'
author: 'nyagato_00'
inputs:
  repo-token:
    description: 'A token for the repo'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-plus'
  color: 'pink'
